### ISSUE TITLE
BUG: Create Menu Item Form Not Working

### ISSUE THREAD

**Issue by robertncole1** [nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1#78]
# User Story
When the create form is triggered for menu item, and the fields are inputted, the form is not submitting

# Acceptance Criteria
Create form should submit and create a new menu item. 

# Dependecies
Dev needs to look at the create menu item function and make sure its working approrpiratly.

**Comment by elliewalkersm** [comment]
removed available key value pair from both create and edit objects in domevents
